# Generated by Django 5.2.2 on 2025-06-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('user_corrected', 'User Corrected')], default='pending', max_length=20)),
                ('queue_type', models.CharField(choices=[('bulk', 'Bulk Import'), ('incremental', 'Incremental Sync'), ('manual', 'Manual Sync'), ('retry', 'Retry')], default='incremental', max_length=20)),
                ('priority', models.IntegerField(default=5, help_text='1=highest, 10=lowest priority')),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Queue',
                'verbose_name_plural': 'Email Queue',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(max_length=50)),
                ('worker_id', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Data extracted from email', null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('email_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='banking.emailqueue')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable template name', max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('subject_patterns', models.JSONField(default=list, help_text='Regex patterns to match email subjects')),
                ('sender_patterns', models.JSONField(default=list, help_text='Regex patterns to match sender emails')),
                ('body_keywords', models.JSONField(default=list, help_text='Keywords that must be present in email body')),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('confidence_threshold', models.FloatField(default=0.8)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('sample_emails_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='banking.bank')),
                ('email_patterns', models.ManyToManyField(related_name='templates', to='banking.emailpattern')),
            ],
            options={
                'verbose_name': 'Bank Template',
                'verbose_name_plural': 'Bank Templates',
                'ordering': ['-updated_at'],
                'unique_together': {('bank', 'name', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['status', 'queue_type'], name='banking_ema_status_ee9fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['user', 'status'], name='banking_ema_user_id_675e38_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['gmail_message_id'], name='banking_ema_gmail_m_1daad7_idx'),
        ),
    ]
