# Generated by Django 5.2.2 on 2025-06-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_emailqueue_emailprocessinglog_banktemplate_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved by User'), ('corrected', 'Corrected by User'), ('rejected', 'Rejected by User')], default='pending', max_length=20)),
                ('review_priority', models.IntegerField(default=5, help_text='1=urgent, 10=low priority')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_merchant', models.CharField(blank=True, max_length=255)),
                ('original_date', models.DateTimeField()),
                ('original_type', models.CharField(max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='User notes about the correction')),
                ('similar_transactions_count', models.IntegerField(default=0)),
                ('auto_apply_corrections', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Review',
                'verbose_name_plural': 'Transaction Reviews',
                'ordering': ['review_priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('amount', 'Amount Correction'), ('merchant', 'Merchant Correction'), ('date', 'Date Correction'), ('type', 'Transaction Type Correction'), ('category', 'Category Assignment')], max_length=20)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('template_updated', models.BooleanField(default=False)),
                ('similar_transactions_updated', models.IntegerField(default=0)),
                ('confidence_improvement', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Correction',
                'verbose_name_plural': 'User Corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_field', models.CharField(help_text='Which regex pattern was improved', max_length=50)),
                ('old_pattern', models.TextField()),
                ('new_pattern', models.TextField()),
                ('improvement_reason', models.TextField()),
                ('accuracy_before', models.FloatField()),
                ('accuracy_after', models.FloatField(blank=True, null=True)),
                ('transactions_reprocessed', models.IntegerField(default=0)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('bank_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='banking.banktemplate')),
                ('user_correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.usercorrection')),
            ],
            options={
                'verbose_name': 'Template Improvement',
                'verbose_name_plural': 'Template Improvements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmailQueue',
        ),
    ]
