# Generated by Django 5.2.2 on 2025-06-12 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Microsoft Outlook'), ('yahoo', 'Yahoo Mail')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_config', models.JSONField(default=dict, help_text='OAuth tokens and provider-specific config')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_message', models.TextField(blank=True, help_text='Reason for last update')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'unique_together': {('user', 'provider', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='EmailImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('suspended', 'Suspended')], default='waiting', max_length=20)),
                ('next_run_at', models.DateTimeField(help_text='When this job should run next')),
                ('retry_after', models.DateTimeField(blank=True, help_text='When to retry after error', null=True)),
                ('period', models.IntegerField(default=30, help_text='Import period in minutes')),
                ('window_start_offset', models.IntegerField(default=0, help_text='Window start offset in minutes')),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, help_text='Status message or error details')),
                ('summary', models.JSONField(default=dict, help_text='Job execution summary: emails_read, emails_created, etc.')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.integration')),
            ],
            options={
                'verbose_name': 'Email Import Job',
                'verbose_name_plural': 'Email Import Jobs',
                'ordering': ['-next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(help_text="Provider's unique message ID", max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('raw_headers', models.JSONField(default=dict)),
                ('attachment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When system created this record')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('process_by', models.CharField(blank=True, help_text='Template ID used for processing', max_length=255)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailimportjob')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.integration')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'indexes': [models.Index(fields=['integration', 'processed_at'], name='core_email_integra_eb3219_idx'), models.Index(fields=['provider_message_id'], name='core_email_provide_4c76f7_idx'), models.Index(fields=['created_at'], name='core_email_created_d71ed9_idx')],
                'unique_together': {('integration', 'provider_message_id')},
            },
        ),
    ]
